services:
  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src/public:/var/www/public:ro
    depends_on:
      - php
    networks:
      - news_aggregator_net

  # PHP-FPM Service
  php:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    image: news-aggregator-app:latest
    env_file:
      - .envs/app.env
    volumes:
      - ../src:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    depends_on:
      - mysql
      - redis
    networks:
      - news_aggregator_net

  # MySQL Database Service
  mysql:
    image: mysql:latest
    env_file:
      - .envs/mysql.env
    volumes:
      - mysql_news_aggregator_db:/var/lib/mysql
    networks:
      - news_aggregator_net

  # Redis Service
  redis:
    image: redis:alpine
    env_file:
      - .envs/redis.env
    networks:
      - news_aggregator_net

  # Laravel Worker
  queue-worker:
    image: news-aggregator-app:latest
    env_file:
      - .envs/app.env
    restart: unless-stopped
    command: php /var/www/artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ../src:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    depends_on:
      - php
    networks:
      - news_aggregator_net

  # Laravel Scheduler
  scheduler:
    image: news-aggregator-app:latest
    env_file:
      - .envs/app.env
    restart: unless-stopped
    command: /bin/sh -c "while :; do php /var/www/artisan schedule:run --verbose --no-interaction & sleep 60; done"
    volumes:
      - ../src:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    depends_on:
      - php
    networks:
      - news_aggregator_net

networks:
  news_aggregator_net:
    driver: bridge

volumes:
  mysql_news_aggregator_db:
