services:
  nginx:
    container_name: web-web-server
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src/public:/var/www/public:ro
    ports:
      - ${HTTP_PORT}:80
      - ${HTTP_PORTS}:443

  php:
    container_name: php-fpm
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    env_file:
      - .envs/app.env
    volumes:
      - ../src:/var/www
